GET http://localhost:8202/api/v1/client/3fa85f64-5717-4562-b3fc-2c963f66afa6/info
Authorization: bearer {{auth_token}}

###

PUT http://localhost:8202/internal/api/v1/client/3fa85f64-5717-4562-b3fc-2c963f66afa6
Authorization: bearer {{auth_token}}
Content-Type: application/json

{
  "name": "name",
  "address": "address",
  "phone": "phone",
  "type": "UL"
}

###